import type { Lesson, MathKey } from "./types";

export const lessons: Lesson[] = [
  {
    id: "quantity",
    index: "01",
    title: "숫자의 발전",
    description: "나뭇가지에서 숫자 10까지",
    example: "10",
    color: "#72bec8",
  },
  {
    id: "addition",
    index: "02",
    title: "덧셈",
    description: "두 무리를 하나로 모으기",
    example: "3+4",
    color: "#9b84d9",
  },
  {
    id: "fast-addition",
    index: "03",
    title: "더 빠른 덧셈",
    description: "열 개씩 묶어 빠르게 더하기",
    example: "10+10",
    color: "#d3a94e",
  },
  {
    id: "multiplication",
    index: "04",
    title: "곱셈",
    description: "가로와 세로의 묶음을 한 번에 세기",
    example: "10×10",
    color: "#9b84d9",
  },
  {
    id: "times-table-two",
    index: "05",
    title: "구구단 2단",
    description: "반복 덧셈을 빠르게 기억하기",
    example: "2×1",
    color: "#72bec8",
  },
  {
    id: "square-area",
    index: "06",
    title: "사각형의 넓이",
    description: "넓이 1인 조각으로 사각형 채우기",
    example: "3×3",
    color: "#9fd8b8",
  },
  {
    id: "triangle-area",
    index: "07",
    title: "삼각형의 넓이",
    description: "사각형으로 삼각형의 넓이 이해하기",
    example: "10",
    color: "#75bde7",
  },
  {
    id: "circle-circumference",
    index: "08",
    title: "원의 둘레",
    description: "지름 · 반지름 · π",
    example: "2×r×π",
    color: "#72bec8",
  },
  {
    id: "circle-area",
    index: "09",
    title: "원의 넓이",
    description: "원 조각 → 사각형",
    example: "π×r²",
    color: "#6fb7ea",
  },
  {
    id: "powers",
    index: "10",
    title: "거듭제곱",
    description: "같은 수를 반복해서 곱하기",
    example: "2×2",
    color: "#b6a5df",
  },
  {
    id: "divisors",
    index: "11",
    title: "약수",
    description: "남김없이 직사각형 만들기",
    example: "12",
    color: "#9b84d9",
  },
  {
    id: "primes-composites",
    index: "12",
    title: "소수와 합성수",
    description: "직사각형 배열로 수 구분하기",
    example: "7",
    color: "#d99a5b",
  },
  {
    id: "prime-factorization",
    index: "13",
    title: "소인수분해",
    description: "소수까지 끝까지 쪼개기",
    example: "12",
    color: "#53aebb",
  },
  {
    id: "multiples",
    index: "14",
    title: "배수",
    description: "같은 간격으로 점프하기",
    example: "2",
    color: "#75bde7",
  },
  {
    id: "common-multiples",
    index: "15",
    title: "공배수",
    description: "두 점프가 겹치는 곳",
    example: "6",
    color: "#b27bc4",
  },
  {
    id: "least-common-multiple",
    index: "16",
    title: "최소공배수",
    description: "두 점프의 첫 만남",
    example: "6",
    color: "#d3a94e",
  },
  {
    id: "common-divisors",
    index: "17",
    title: "공약수",
    description: "둘 다 남김없이 묶기",
    example: "12",
    color: "#68b58d",
  },
  {
    id: "greatest-common-divisor",
    index: "18",
    title: "최대공약수",
    description: "가장 큰 공통 묶음",
    example: "18",
    color: "#d99a5b",
  },
  {
    id: "powers-two",
    index: "19",
    title: "거듭제곱 2",
    description: "8을 2의 세제곱으로 바꾸어 보기",
    example: "2×8",
    color: "#8d78c9",
  },
  {
    id: "subtraction",
    index: "20",
    title: "뺄셈",
    description: "전체에서 일부 덜어내기",
    example: "7-3",
    color: "#d98291",
  },
  {
    id: "division",
    index: "21",
    title: "나눗셈",
    description: "같은 크기의 그룹으로 나누기",
    example: "12÷3",
    color: "#68b58d",
  },
  {
    id: "parentheses",
    index: "22",
    title: "괄호",
    description: "먼저 계산할 세계 묶기",
    example: "(4+2)×3",
    color: "#739fda",
  },
  {
    id: "mixed",
    index: "23",
    title: "복합 계산",
    description: "연산의 순서 탐험하기",
    example: "8÷2+3",
    color: "#b27bc4",
  },
  {
    id: "explore",
    index: "24",
    title: "자유 탐구",
    description: "나만의 식으로 공간 바꾸기",
    example: "6+3",
    color: "#72bec8",
  },
];

export function getLessonIdFromQuery(value: string | null) {
  return value && lessons.some((lesson) => lesson.id === value) ? value : lessons[0].id;
}

export const numberKeys: MathKey[] = [
  { value: "7", color: "bg-[#242424]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "8", color: "bg-[#2a2a2a]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "9", color: "bg-[#242424]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "4", color: "bg-[#2a2a2a]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "5", color: "bg-[#242424]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "6", color: "bg-[#2a2a2a]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "1", color: "bg-[#242424]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "2", color: "bg-[#2a2a2a]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "3", color: "bg-[#242424]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
  { value: "0", color: "bg-[#2a2a2a]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-[#f5f5f5]" },
];

export const operatorKeys: MathKey[] = [
  { value: "+", color: "bg-[#353535]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-white" },
  { value: "-", color: "bg-[#353535]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-white" },
  { value: "×", color: "bg-[#353535]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-white" },
  { value: "÷", color: "bg-[#353535]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-white" },
  { value: "(", color: "bg-[#353535]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-white" },
  { value: ")", color: "bg-[#353535]", shadow: "shadow-[0_5px_0_#0a0a0a]", text: "text-white" },
];
