create table if not exists public."QuizProgress" (
  id bigint generated by default as identity primary key,
  "studentName" text not null check (length(trim("studentName")) > 0),
  "quizIndex" integer not null check ("quizIndex" between 0 and 99),
  "solveCount" integer not null default 0 check ("solveCount" between 0 and 3),
  "updatedAt" timestamptz not null default now(),
  unique ("studentName", "quizIndex")
);

alter table public."QuizProgress" enable row level security;

create or replace function public.save_quiz_progress(
  p_student_name text,
  p_quiz_index integer,
  p_solve_count integer
)
returns table (
  "studentName" text,
  "quizIndex" integer,
  "solveCount" integer
)
language sql
security definer
set search_path = public
as $$
  insert into public."QuizProgress" as progress (
    "studentName",
    "quizIndex",
    "solveCount",
    "updatedAt"
  )
  values (trim(p_student_name), p_quiz_index, least(3, greatest(0, p_solve_count)), now())
  on conflict ("studentName", "quizIndex") do update
  set
    "solveCount" = greatest(progress."solveCount", excluded."solveCount"),
    "updatedAt" = now()
  returning
    progress."studentName",
    progress."quizIndex",
    progress."solveCount";
$$;

revoke all on function public.save_quiz_progress(text, integer, integer) from public;
revoke all on function public.save_quiz_progress(text, integer, integer) from anon;
revoke all on function public.save_quiz_progress(text, integer, integer) from authenticated;
grant execute on function public.save_quiz_progress(text, integer, integer) to service_role;
